## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("d:/SUMAN/dataset_pandas/csec_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58%,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67%,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0%,Critical,36 more,Never,12

#### Section 1: Data Inspection

In [ ]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------

In [3]:

print("First 10 rows:")
display(df.head(10))

print("\nShape of the DataFrame:")
print(df.shape)

print("\nData types of each column:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
5,4MW24CS128,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
6,4MW24CS130,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
7,4MW24CS131,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
8,4MW24CS132,SANYA,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25%,Critical,24 more,2026-09-25,3

Shape of the DataFrame:
(65, 12)

Data types of each column:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [ ]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------

In [4]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nColumns with null values:")
null_counts = df.isnull().sum()
print(null_counts[null_counts > 0])

print("\nCount of 'Never' values in Last Present Date:")
never_count = df["Last Present Date"].astype(str).str.strip().str.lower().eq("never").sum()
print(never_count)

print("\nSummary:")
print("Total null values in DataFrame:", df.isnull().sum().sum())
print("'Never' values in Last Present Date:", never_count)

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Columns with null values:
Series([], dtype: int64)

Count of 'Never' values in Last Present Date:
3

Summary:
Total null values in DataFrame: 0
'Never' values in Last Present Date: 3

In [ ]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------

In [5]:
import re

df.columns = [
    re.sub(r'[^a-zA-Z0-9]+', '_', col.strip()).strip('_').lower()
    for col in df.columns
]

df.rename(columns={'attendance': 'attendance_pct'}, inplace=True)

print("Updated column names:")
print(df.columns.tolist())

Updated column names:
['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

In [ ]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------

In [6]:
df['attendance_pct'] = (
    df['attendance_pct']
    .astype(str)
    .str.replace('%', '', regex=False)
    .astype(float)
)

df['last_present_date'] = pd.to_datetime(
    df['last_present_date'].replace('Never', pd.NaT),
    errors='coerce'
)

print(df[['attendance_pct', 'last_present_date']].dtypes)
print(df[['attendance_pct', 'last_present_date']].head())

attendance_pct              float64
last_present_date    datetime64[us]
dtype: object
   attendance_pct last_present_date
0           100.0        2026-10-09
1            92.0        2026-10-07
2            17.0        2026-09-25
3            75.0        2026-10-09
4            83.0        2026-10-07

#### Section 2: Filtering & Selection

In [ ]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------

In [7]:
critical_students = df[df['status'] == 'Critical'].sort_values(
    by='attendance_pct',
    ascending=True
)

display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-09,9
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25.0,Critical,24 more,2026-09-25,3
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,33.0,Critical,20 more,2026-10-07,1
41,4MW24CS165,SUNIL BHAT,Data Science & GenAI - 3nd Yr - CSE - C,11,5,6,0,45.0,Critical,13 more,2026-10-07,1
15,4MW24CS139,SHLOAG MAHESH BANT,Data Science & GenAI - 3nd Yr - CSE - C,12,6,6,0,50.0,Critical,12 more,2026-10-07,1
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58.0,Critical,8 more,2026-10-09,0
30,4MW24CS154,SHREYAS SATISH BHAT,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
11,4MW24CS135,SATHWIK G KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
17,4MW24CS141,SHRAVAN,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
58,4MW24CS182,VISHNU PRASAD,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
51,4MW24CS175,THEJAS B K,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-09-25,3
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
34,4MW24CS158,SINDHU,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1

In [ ]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------

In [8]:
fully_absent = df[df['present'] == 0][
    ['roll_no', 'student_name', 'consecutive_absences']
]

display(fully_absent)

       roll_no        student_name  consecutive_absences
20  4MW24CS144  SHREEHARI SHENOY R                    12
43  4MW24CS167             SURAJ R                    12
64  4MW25CS409            YASHVITH                    12

In [ ]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------

In [9]:
safe_students = df.loc[df['status'] == 'Safe']
display(safe_students)

display(df.iloc[:15, 1:6])

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1
5,4MW24CS128,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
6,4MW24CS130,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
7,4MW24CS131,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
12,4MW24CS136,SHARANYA THANTRY,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
14,4MW24CS138,SHEETAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1
18,4MW24CS142,SHRAVYA R K,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
23,4MW24CS147,SHREYA (JAYANTH ),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
26,4MW24CS150,SHREYA (VIJAYENDRA),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
28,4MW24CS152,SHREYA PRABHU,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
29,4MW24CS153,SHREYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
36,4MW24CS160,SOWJANYA (SUNDARA),Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
39,4MW24CS163,SUMAN,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
42,4MW24CS166,SUPRIYA NAIK,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
47,4MW24CS171,SUSHANTH-(SHIVANANDA SAPALIGA),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
48,4MW24CS172,SWASTHIK ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
50,4MW24CS174,THARUN S,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
54,4MW24CS178,VARSHA V PRABHU,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
57,4MW24CS181,VINEETH,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0

,student_name,subject,total_classes,present,absent
0,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0
1,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1
2,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10
3,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3
4,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2
5,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1
6,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1
7,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0
8,SANYA,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3
9,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9
10,SARTHAK,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2
11,SATHWIK G KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4
12,SHARANYA THANTRY,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1
13,SHASHANK KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3
14,SHEETAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1

In [ ]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------

In [10]:
students = df.loc[
    df['consecutive_absences'] >= 5,
    ['student_name', 'status', 'last_present_date']
]

display(students)

          student_name    status last_present_date
20  SHREEHARI SHENOY R  Critical               NaT
43             SURAJ R  Critical               NaT
45    SUSHAN S POOJARY  Critical        2026-09-04
53     UTHSAV N SHETTY  Critical        2026-09-09
62   SANATH S DEVADIGA  Critical        2026-09-04
63            SUSHANTH  Critical        2026-09-04
64            YASHVITH  Critical               NaT

### Section 3: Grouping & Aggregation

In [ ]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------

In [11]:
status_summary = df.groupby('status').agg(
    student_count=('student_name', 'count'),
    average_attendance_pct=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
).reset_index()

display(status_summary)

     status  student_count  average_attendance_pct  max_consecutive_absences
0  Critical             21               38.333333                        12
1      Safe             20               94.400000                         1
2   Warning             24               80.000000                         1

In [ ]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------

In [13]:


df['attendance_pct'] = pd.to_numeric(df['attendance_pct'], errors='coerce')

conditions = [
    df['attendance_pct'] >= 90,
    (df['attendance_pct'] >= 75) & (df['attendance_pct'] < 90),
    (df['attendance_pct'] >= 60) & (df['attendance_pct'] < 75),
    df['attendance_pct'] < 60
]

categories = ['Excellent', 'Good', 'Average', 'Poor']

df['attendance_category'] = np.select(
    conditions,
    categories,
    default='Unknown'
)

category_counts = df.groupby('attendance_category').size().reset_index(
    name='student_count'
)

display(category_counts)

  attendance_category  student_count
0             Average              8
1           Excellent             20
2                Good             24
3                Poor             13

In [ ]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------

In [14]:
summary = df.agg({
    'total_classes': 'sum',
    'present': 'sum',
    'absent': 'sum'
})

print(summary)

total_classes    779
present          553
absent           226
dtype: int64

In [ ]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------

In [15]:
status_summary = df.groupby('status').agg(
    present_min=('present', 'min'),
    present_max=('present', 'max'),
    present_mean=('present', 'mean'),
    total_absent=('absent', 'sum')
)

display(status_summary)

          present_min  present_max  present_mean  total_absent
status
Critical            0            8      4.571429           155
Safe               11           12     11.300000            14
Warning             9           10      9.625000            57

### Section 4: Feature Engineering & Transformation

In [ ]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------

In [16]:
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)

top_10_risk = df.sort_values(by='risk_score', ascending=False).head(10)

display(top_10_risk)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-09,9,Poor,9.4
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3,Poor,5.8
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25.0,Critical,24 more,2026-09-25,3,Poor,5.4
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,33.0,Critical,20 more,2026-10-07,1,Poor,3.8

In [ ]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------

In [20]:
col = next(c for c in df.columns if 'classes_needed' in c.lower())

df['classes_needed_numeric'] = (
    df[col].astype(str)
    .str.extract(r'(\d+)')[0]
    .fillna(0)
    .astype(int)
)

display(df[[col, 'classes_needed_numeric']].head(10))

  classes_needed_75  classes_needed_numeric
0             ✓ Met                       0
1             ✓ Met                       0
2           28 more                      28
3             ✓ Met                       0
4             ✓ Met                       0
5             ✓ Met                       0
6             ✓ Met                       0
7             ✓ Met                       0
8             ✓ Met                       0
9           24 more                      24

In [ ]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------

In [21]:
df['attendance_flag'] = df['attendance_pct'].apply(
    lambda x: 'Defaulter' if x < 75 else 'Safe'
)

display(df[['student_name', 'attendance_pct', 'attendance_flag']])

         student_name  attendance_pct attendance_flag
0       SAKSHI SHETTY           100.0            Safe
1     SAMEEKSHA BEKAL            92.0            Safe
2      SAMEER ACHARYA            17.0       Defaulter
3       SAMHITA S RAO            75.0            Safe
4            SAMIKSHA            83.0            Safe
..                ...             ...             ...
60        RIYA SHETTY            58.0       Defaulter
61            ANIRUDH            67.0       Defaulter
62  SANATH S DEVADIGA             8.0       Defaulter
63           SUSHANTH             8.0       Defaulter
64           YASHVITH             0.0       Defaulter

[65 rows x 3 columns]

In [ ]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------

In [22]:
df['attendance_range'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, 100],
    labels=['Critical', 'Warning', 'Good', 'Excellent'],
    include_lowest=True
)

display(df[['student_name', 'attendance_pct', 'attendance_range']])

         student_name  attendance_pct attendance_range
0       SAKSHI SHETTY           100.0        Excellent
1     SAMEEKSHA BEKAL            92.0        Excellent
2      SAMEER ACHARYA            17.0         Critical
3       SAMHITA S RAO            75.0          Warning
4            SAMIKSHA            83.0             Good
..                ...             ...              ...
60        RIYA SHETTY            58.0          Warning
61            ANIRUDH            67.0          Warning
62  SANATH S DEVADIGA             8.0         Critical
63           SUSHANTH             8.0         Critical
64           YASHVITH             0.0         Critical

[65 rows x 3 columns]

### Section 5: Advanced Analysis

In [ ]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------

In [23]:
pivot_summary = pd.pivot_table(
    df,
    index='status',
    columns='attendance_category',
    values='student_name',
    aggfunc='count',
    fill_value=0
)

display(pivot_summary)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   8          0     0    13
Safe                       0         20     0     0
Warning                    0          0    24     0

In [ ]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

In [24]:
df['base_name'] = df['student_name'].str.split('(').str[0].str.strip()

duplicate_names = df[df.duplicated(subset='base_name', keep=False)].sort_values('base_name')

display(duplicate_names)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
23,4MW24CS147,SHREYA (JAYANTH ),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,SHREYA
24,4MW24CS148,SHREYA(SATHYANARAYANA ACHARI),Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-07,1,Good,1.4,0,Safe,Good,SHREYA
25,4MW24CS149,SHREYA(SHIVANANDA MARAKALA G),Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,Safe,Good,SHREYA
26,4MW24CS150,SHREYA (VIJAYENDRA),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,Safe,Excellent,SHREYA
36,4MW24CS160,SOWJANYA (SUNDARA),Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,SOWJANYA
37,4MW24CS161,SOWJANYA(GURU),Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,0,Good,1.2,0,Safe,Warning,SOWJANYA
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0,Average,1.6,4,Defaulter,Warning,SUSHANTH
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter,Critical,SUSHANTH

In [ ]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

In [25]:
student_details = pd.DataFrame({
    'roll_no': df['roll_no'],
    'branch': 'CSE',
    'semester': 5
})

merged_df = pd.merge(
    df,
    student_details,
    on='roll_no',
    how='inner'
)

display(merged_df)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,0,Safe,Excellent,SAKSHI SHETTY,CSE,5
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1,Excellent,1.0,0,Safe,Excellent,SAMEEKSHA BEKAL,CSE,5
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3,Poor,5.8,28,Defaulter,Critical,SAMEER ACHARYA,CSE,5
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,0,Good,1.2,0,Safe,Warning,SAMHITA S RAO,CSE,5
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-07,1,Good,1.4,0,Safe,Good,SAMIKSHA,CSE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58.0,Critical,8 more,2026-10-09,0,Poor,2.0,8,Defaulter,Warning,RIYA SHETTY,CSE,5
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1,Average,2.2,4,Defaulter,Warning,ANIRUDH,CSE,5
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter,Critical,SANATH S DEVADIGA,CSE,5
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4,32,Defaulter,Critical,SUSHANTH,CSE,5
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,YASHVITH,CSE,5

In [ ]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

In [26]:
critical_students = df[df['status'] == 'Critical']
critical_students.to_csv('critical_students.csv', index=False)

status_summary = df.groupby('status').agg(
    student_count=('student_name', 'count'),
    average_attendance_pct=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
).reset_index()
status_summary.to_csv('status_summary.csv', index=False)

top_10_risk = df.sort_values(
    by='risk_score', ascending=False
).head(10)
top_10_risk.to_csv('top_10_risk_students.csv', index=False)

print("CSV files exported successfully.")

CSV files exported successfully.